### ISSUE TITLE
The overlay is not rendered in Dirt Rally 2.0. But it seems to work without the GUI.

### ISSUE THREAD

**Issue by DKHSG** [retroluxfilm/reshade-vrtoolkit#3] opened 2021-08-05 08:54 UTC

**Comment by retroluxfilm** [comment] 2021-08-05 19:59
So you see the effect but the reshade icon is missing in the Steam VR dashboard? Need to download DR2 again to check it myself to help you out.

**Comment by DKHSG** [comment] 2021-08-06 07:26
The reshade icon is on the panel. I can click on it and i see the headline VRToolkit 0.9.2 or something. But the configuration menu is not rendered. I`m on WMR btw.

**Comment by retroluxfilm** [comment] 2021-08-06 20:31
Yes I can confirm that the reshade menu is not properly rendered but the effect itself is working fine. (on Index as well) 

Here is a workaround until it is fixed:

1. Open the reshade settings on the desktop mirror. **CTRL+POS1/HOME** hotkey
2. Press the load effects button so that vrtoolkit.fx is loaded
3. Adjust preset settings
4. Restar the game.

**Comment by retroluxfilm** [comment] 2024-02-04 21:43
Its fixed with the latest version

**Closed by retroluxfilm** 2024-02-04 21:43 UTC
Labels: bug, Reshade

**Comment by Pavelo77** [comment] 2025-10-01 09:42
Hi, I tried for hours to make it work with my Quest 2 but it renders just in the window and not in the visor, tried different reshade versions with no luck, no icon in the Steam overlay either, any advice? Works for me with RBR and HL:ALYX, doesn't work with DR and DR2.0
